package com.hzcominfo.governtool.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hzcominfo.governtool.bean.SettingBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SETTING_BEAN".
*/
public class SettingBeanDao extends AbstractDao<SettingBean, Long> {

    public static final String TABLENAME = "SETTING_BEAN";

    /**
     * Properties of entity SettingBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IsAutoPhoto = new Property(1, Boolean.class, "isAutoPhoto", false, "IS_AUTO_PHOTO");
        public final static Property PhotoInterval = new Property(2, String.class, "photoInterval", false, "PHOTO_INTERVAL");
        public final static Property IsWalk = new Property(3, boolean.class, "isWalk", false, "IS_WALK");
    }


    public SettingBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SettingBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SETTING_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"IS_AUTO_PHOTO\" INTEGER," + // 1: isAutoPhoto
                "\"PHOTO_INTERVAL\" TEXT," + // 2: photoInterval
                "\"IS_WALK\" INTEGER NOT NULL );"); // 3: isWalk
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SETTING_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SettingBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isAutoPhoto = entity.getIsAutoPhoto();
        if (isAutoPhoto != null) {
            stmt.bindLong(2, isAutoPhoto ? 1L: 0L);
        }
 
        String photoInterval = entity.getPhotoInterval();
        if (photoInterval != null) {
            stmt.bindString(3, photoInterval);
        }
        stmt.bindLong(4, entity.getIsWalk() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SettingBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean isAutoPhoto = entity.getIsAutoPhoto();
        if (isAutoPhoto != null) {
            stmt.bindLong(2, isAutoPhoto ? 1L: 0L);
        }
 
        String photoInterval = entity.getPhotoInterval();
        if (photoInterval != null) {
            stmt.bindString(3, photoInterval);
        }
        stmt.bindLong(4, entity.getIsWalk() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SettingBean readEntity(Cursor cursor, int offset) {
        SettingBean entity = new SettingBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // isAutoPhoto
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // photoInterval
            cursor.getShort(offset + 3) != 0 // isWalk
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SettingBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsAutoPhoto(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setPhotoInterval(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsWalk(cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SettingBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SettingBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SettingBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
